### ISSUE TITLE
希望能支持一下新功能：文本比对、在线时间戳

### ISSUE THREAD

**Issue by shirayner** [rockbenben/tools-by-ai#1]
希望能新增的功能：

- 文本比对： 示例网站 [https://www.jq22.com/textDifference](https://www.jq22.com/textDifference)
- 在线时间戳：示例完整 https://tool.lu/timestamp/

**Comment by rockbenben** [comment]
看起来你提供的那两个功能在你给的示例网站上运作得相当好。

对于新功能，我倾向于避免重复造轮子，尤其是在已经有成熟方案的情况下。我希望把精力投入到还没有好的解决方案或者我们能够做得更好的地方。当然，如果你有任何特别的需求或者觉得现有的工具有什么不足，欢迎随时跟我说，我们一起讨论看看怎么做最好。

**Comment by shirayner** [comment]
嗯嗯，也可以的
