### ISSUE TITLE
【文本分割】能不能增加导出为txt的功能?

### ISSUE THREAD

**Issue by Noah1995** [rockbenben/tools-by-ai#18]
多段分别导出！
或者多段导出为1个（长文一段一段复制好麻烦）（最好可以设置每段添加换行符）

**Comment by rockbenben** [comment]
好建议，更新了。https://github.com/rockbenben/tools-by-ai/commit/837a5ddb1c1cd720ff0c2188f484447b0b97118e

**Comment by Noah1995** [comment]
> 好建议，更新了。[837a5dd](https://github.com/rockbenben/tools-by-ai/commit/837a5ddb1c1cd720ff0c2188f484447b0b97118e)

可以用了
TXT标题能否默认使用txt文本第一行前面部分
或者自定义（如果多个txt就自定义+1丶2丶3这样1）

**Comment by rockbenben** [comment]
整行容易出bug，添加了自定义文件名
